/*
 * RandomTest.cpp
 * This file contains the unit tests of the Random class. Since the generated values are random,
 * the tests check the properties that every generated value must satisfy (ranges, lengths, etc.)
 * over a large number of samples, and that a fixed seed reproduces the same sequence.
 */

#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

#include <gtest/gtest.h>

#include "core/utils/random/Random.h"

namespace
{
	constexpr int   SAMPLE_COUNT{ 1000 }; // number of values generated by each test
	constexpr float TOLERANCE{ 1e-4f };   // tolerance of the floating-point comparisons
} // namespace

TEST(RandomTest, GenerateRandomFloatStaysWithinTheRange)
{
	Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const float value = random.generate_random_float(-2.5f, 4.0f);
		EXPECT_GE(value, -2.5f);
		EXPECT_LE(value, 4.0f);
	}
}

TEST(RandomTest, GenerateRandomColorHasNormalizedComponentsAndIsOpaque)
{
	Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const glm::vec4 color = random.generate_random_color();
		for (int component = 0; component < 3; ++component)
		{
			EXPECT_GE(color[component], 0.0f);
			EXPECT_LE(color[component], 1.0f);
		}
		EXPECT_FLOAT_EQ(color.a, 1.0f);
	}
}

TEST(RandomTest, GenerateRandomPositionStaysWithinTheDistanceRange)
{
	Random          random{};
	const glm::vec3 target{ 5.0f, -3.0f, 2.0f };
	bool            has_negative_offset{ false }; // whether any position lies on the negative side of the target
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const glm::vec3 position = random.generate_random_position(target, 2.0f, 6.0f);
		const float     distance = glm::distance(position, target);

		EXPECT_GE(distance, 2.0f - TOLERANCE);
		EXPECT_LE(distance, 6.0f + TOLERANCE);

		const glm::vec3 offset = position - target;
		has_negative_offset |= offset.x < 0.0f || offset.y < 0.0f || offset.z < 0.0f;
	}
	// the positions are spread in every direction around the target (not only on the positive side)
	EXPECT_TRUE(has_negative_offset);
}

TEST(RandomTest, GenerateRandomDirectionIsAUnitVector)
{
	Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		EXPECT_NEAR(glm::length(random.generate_random_direction()), 1.0f, TOLERANCE);
	}
}

TEST(RandomTest, GenerateRandomRotationIsAUnitQuaternion)
{
	Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		EXPECT_NEAR(glm::length(random.generate_random_rotation()), 1.0f, TOLERANCE);
		EXPECT_NEAR(glm::length(random.generate_random_rotation(10.0f, 90.0f)), 1.0f, TOLERANCE);
	}
}

TEST(RandomTest, GenerateRandomRotationWithAnAxisStaysWithinTheAngleRange)
{
	Random          random{};
	const glm::vec3 axis{ 0.0f, 2.0f, 0.0f }; // not normalized on purpose (the method normalizes it)
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const glm::quat rotation = random.generate_random_rotation(30.0f, 60.0f, axis);
		const float     angle    = glm::degrees(glm::angle(rotation));

		EXPECT_GE(angle, 30.0f - TOLERANCE);
		EXPECT_LE(angle, 60.0f + TOLERANCE);
		EXPECT_NEAR(glm::dot(glm::axis(rotation), glm::vec3{ 0.0f, 1.0f, 0.0f }), 1.0f, TOLERANCE);
	}
}

TEST(RandomTest, SameSeedGeneratesTheSameSequence)
{
	Random first{ 42u };
	Random second{ 42u };
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		EXPECT_EQ(first.generate_random_float(0.0f, 1.0f), second.generate_random_float(0.0f, 1.0f));
	}
}

TEST(RandomTest, DifferentSeedsGenerateDifferentSequences)
{
	Random first{ 1u };
	Random second{ 2u };
	int    equal_values{ 0 };
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		if (first.generate_random_float(0.0f, 1.0f) == second.generate_random_float(0.0f, 1.0f))
			++equal_values;
	}
	EXPECT_LT(equal_values, SAMPLE_COUNT);
}
