/*
 * Random_Test.cpp
 * This file contains the unit tests of the Random class. Since the generated values are random,
 * the tests check the properties that every generated value must satisfy (ranges, lengths, etc.)
 * over a large number of samples.
 */

#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

#include <gtest/gtest.h>

#include "core/utils/random/Random.h"

namespace
{
	constexpr int   SAMPLE_COUNT{ 1000 }; // number of values generated by each test
	constexpr float TOLERANCE{ 1e-4f };   // tolerance of the floating-point comparisons
} // namespace

TEST(Random_Test, generate_random_float_stays_within_the_range)
{
	const Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const float value = random.generate_random_float(-2.5f, 4.0f);
		EXPECT_GE(value, -2.5f);
		EXPECT_LE(value, 4.0f);
	}
}

TEST(Random_Test, generate_random_color_has_normalized_components_and_is_opaque)
{
	const Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const glm::vec4 color = random.generate_random_color();
		for (int component = 0; component < 3; ++component)
		{
			EXPECT_GE(color[component], 0.0f);
			EXPECT_LE(color[component], 1.0f);
		}
		EXPECT_FLOAT_EQ(color.a, 1.0f);
	}
}

TEST(Random_Test, generate_random_direction_is_a_unit_vector)
{
	const Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		EXPECT_NEAR(glm::length(random.generate_random_direction()), 1.0f, TOLERANCE);
	}
}

TEST(Random_Test, generate_random_rotation_is_a_unit_quaternion)
{
	const Random random{};
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		EXPECT_NEAR(glm::length(random.generate_random_rotation()), 1.0f, TOLERANCE);
		EXPECT_NEAR(glm::length(random.generate_random_rotation(10.0f, 90.0f)), 1.0f, TOLERANCE);
	}
}

TEST(Random_Test, generate_random_rotation_with_an_axis_stays_within_the_angle_range)
{
	const Random    random{};
	const glm::vec3 axis{ 0.0f, 2.0f, 0.0f }; // not normalized on purpose (the method normalizes it)
	for (int i = 0; i < SAMPLE_COUNT; ++i)
	{
		const glm::quat rotation = random.generate_random_rotation(30.0f, 60.0f, axis);
		const float     angle    = glm::degrees(glm::angle(rotation));

		EXPECT_GE(angle, 30.0f - TOLERANCE);
		EXPECT_LE(angle, 60.0f + TOLERANCE);
		EXPECT_NEAR(glm::dot(glm::axis(rotation), glm::vec3{ 0.0f, 1.0f, 0.0f }), 1.0f, TOLERANCE);
	}
}
